"""Generate the Markdown report for the Task 1 write-up.

Every number comes from the ``ImpactReport`` and ``LabelSummary``; every sentence about strengths
and limitations comes from ``rationale.yaml``, which a human wrote. Nothing in here is invented
at runtime except the Bedrock explanation, which is clearly attributed as generated.
"""

from __future__ import annotations

from importlib import resources
from typing import Any

import yaml

from sentiment_prep.analysis.comprehend_text import TRUNCATION_WARNING, prepare_text
from sentiment_prep.labeling import service as labeling
from sentiment_prep.models import DatasetBundle
from sentiment_prep.presentation import public_report


def load_rationale() -> dict[str, dict[str, str]]:
    """Read the per-step rationale shipped with the package."""
    text = resources.files("sentiment_prep.resources").joinpath("rationale.yaml").read_text()
    data: dict[str, dict[str, str]] = yaml.safe_load(text)
    return data


def render_report(bundle: DatasetBundle, *, diagnostics: bool = False) -> str:
    """Return the Markdown document."""
    rationale = load_rationale()
    lines: list[str] = ["# Sentiment dataset preparation report", ""]
    lines += _dataset_section(bundle, diagnostics=diagnostics)
    lines += _labels_section(bundle)
    from sentiment_prep.storage.checkpoints import checkpoint_warnings

    lines += [f"- Warning: {warning}" for warning in checkpoint_warnings(bundle)]

    if not bundle.report:
        lines += ["No preprocessing has been run on this dataset yet.", ""]
        return "\n".join(lines)

    lines += ["## Preprocessing steps applied", ""]
    for index, name in enumerate(bundle.applied_steps, start=1):
        entry = rationale.get(name, {})
        lines.append(f"{index}. **{entry.get('title', name)}**: {entry.get('summary', '')}")
    lines.append("")

    lines += _impact_section(bundle, diagnostics=diagnostics)

    if bundle.report.explanation:
        lines += [
            "## Generated interpretation",
            "",
            "_Generated by an LLM from the numbers above; "
            "review this interpretation before quoting it._",
            "",
            bundle.report.explanation,
            "",
        ]

    lines += ["## Strengths and limitations of the selected techniques", ""]
    for name in bundle.applied_steps:
        step_entry = rationale.get(name)
        if not step_entry:
            continue
        entry = step_entry
        lines += [
            f"### {entry['title']}",
            "",
            f"**Strengths.** {entry['strengths'].strip()}",
            "",
            f"**Limitations.** {entry['limitations'].strip()}",
            "",
        ]
    return "\n".join(lines)


def _dataset_section(bundle: DatasetBundle, *, diagnostics: bool) -> list[str]:
    original = bundle.original
    lines = ["## Dataset", ""]
    lines.append(
        f"- Source: `{original.source_type}`"
        + (f" (query: `{original.query}`)" if original.query else "")
    )
    lines.append(f"- Fetched: {original.fetched_at.strftime('%Y-%m-%d %H:%M UTC')}")
    if original.window_start or original.window_end:
        started = (
            original.window_start.strftime("%Y-%m-%d %H:%M")
            if original.window_start
            else "7 days ago"
        )
        ended = original.window_end.strftime("%Y-%m-%d %H:%M") if original.window_end else "now"
        lines.append(f"- Search window (UTC): {started} to {ended}")
    dropped_at_source = sum(original.filtered_out.values())
    if dropped_at_source:
        lines.append(f"- Posts returned by the source: {len(original.records) + dropped_at_source}")
        for reason, count in sorted(original.filtered_out.items()):
            lines.append(f"  - dropped at collection ({reason.replace('_', ' ')}): {count}")
    lines.append(f"- Records collected: {len(original.records)}")
    if bundle.processed is not None:
        removed = len(original.records) - len(bundle.processed.records)
        lines.append(
            f"- Records after preprocessing: {len(bundle.processed.records)}"
            + (f" ({removed} emptied by the steps and dropped)" if removed else "")
        )
    if original.truncated_reason:
        lines.append(f"- Note: fetch stopped early ({original.truncated_reason})")
    if diagnostics:
        for stage, uri in sorted(bundle.checkpoints.items()):
            lines.append(f"- Checkpoint `{stage}`: `{uri}`")
    lines.append("")
    return lines


def _labels_section(bundle: DatasetBundle) -> list[str]:
    labels = labeling.summary(bundle)
    if not labels.labelled and not bundle.label_failures:
        return []
    lines = ["## Labels", ""]
    lines.append(f"- Labelled records: {labels.labelled} of {labels.total}")
    if any(r.comprehend_label and prepare_text(r.text).truncated for r in bundle.original.records):
        lines.append(f"- Warning: {TRUNCATION_WARNING}")
    if bundle.label_failures:
        lines.append(
            f"- Records without a successful Comprehend result: {len(bundle.label_failures)}"
        )
    for source, count in sorted(labels.by_source.items()):
        lines.append(f"- From {source}: {count}")
    lines.append(
        "- Distribution: " + ", ".join(f"{k} {v}" for k, v in sorted(labels.by_label.items()))
    )
    if labels.review_sample_size:
        lines.append(f"- Manual review: {labels.reviewed} of {labels.review_sample_size} reviewed")
    if labels.manual_vs_comprehend_agreement is not None:
        lines.append(
            "- Reviewer vs Comprehend agreement: "
            f"**{labels.manual_vs_comprehend_agreement:.1%}** over "
            f"{labels.comparable_records} comparable records "
            f"({labels.disagreements} disagreements)"
        )
    lines.append("")
    return lines


def _impact_section(bundle: DatasetBundle, *, diagnostics: bool) -> list[str]:
    """Render the measured-impact table. Caller guarantees ``bundle.report`` is set."""
    if bundle.report is None:
        return []
    lines = ["## Measured impact", ""]
    lines.append(
        "| Step | Records in | Records out | Vocab before | Vocab after "
        "| Avg tokens before | Avg tokens after |"
    )
    lines.append("|---|---|---|---|---|---|---|")
    for step in bundle.report.steps:
        lines.append(
            f"| {step.step_name} | {step.records_in} | {step.records_out} | {step.vocab_before} "
            f"| {step.vocab_after} | {step.avg_tokens_before} | {step.avg_tokens_after} |"
        )
    lines.append("")
    if bundle.report.sentiment:
        s = bundle.report.sentiment
        agreement = f"{s.agreement:.1%}" if s.agreement is not None else "unavailable"
        lines.append(
            "Baseline sentiment (Amazon Comprehend) agreement before vs after: "
            f"**{agreement}** over {s.comparable_records} successful comparable records "
            f"of {s.shared_records} shared records. "
            f"Distribution before: {_fmt(s.distribution_before)}. "
            f"After: {_fmt(s.distribution_after)}."
        )
    if bundle.report.embedding_drift is not None:
        lines.append(
            "Mean embedding drift (Titan Embed v2, cosine distance): "
            f"**{bundle.report.embedding_drift}**."
        )
    for warning in public_report(bundle.report, diagnostics=diagnostics).warnings:
        lines.append(f"- Warning: {warning}")
    lines.append("")
    return lines


def _fmt(distribution: dict[str, Any]) -> str:
    return ", ".join(f"{k.lower()} {v}" for k, v in sorted(distribution.items()))
