/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate an operator without distributing the permanent key in public assets.
         */
        post: operations["login_auth_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Liveness and, only with diagnostics on, the facts an operator checks first.
         *
         *     Never touches paid services. Operator-only fields are omitted unless diagnostics are enabled so
         *     a public deployment reveals nothing about its storage or which paid services are switched on.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch from X or Hugging Face
         * @description Fetch up to ``limit`` records.
         *
         *     X fetches are billed per post and capped (``X_MAX_READS_PER_FETCH``, ``X_MAX_READS_PER_DAY``).
         *     If the client disconnects mid-fetch the paging loop stops at the next page boundary so no
         *     further reads are billed. The ``collected`` checkpoint is written before returning.
         */
        post: operations["load_dataset_dataset_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a CSV
         * @description CSV with a ``text`` column and optional ``label``/``id`` columns.
         */
        post: operations["upload_dataset_dataset_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dataset summary
         * @description Summary and preview of a previously loaded dataset.
         */
        get: operations["get_dataset_dataset__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page through records
         * @description Original records joined with their processed version (null if dropped).
         */
        get: operations["get_records_dataset__dataset_id__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available steps
         * @description Catalogue of steps with their human-written rationale, in the recommended order.
         */
        get: operations["list_steps_steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/preprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run preprocessing and measure impact
         * @description Apply steps in order. Always re-runs from the original data, so toggles are idempotent.
         *
         *     Comprehend, Titan embeddings and Bedrock are best-effort: if any is disabled or fails the
         *     corresponding report field is null and ``report.warnings`` says why. The ``processed``
         *     checkpoint is rewritten on every run.
         */
        post: operations["preprocess_dataset__dataset_id__preprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/labels/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Label coverage and agreement
         * @description Counts by source and label, review progress, reviewer-vs-Comprehend agreement.
         */
        get: operations["label_summary_dataset__dataset_id__labels_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/labels/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comprehend cost estimate
         * @description Billable units, and dollars when the current rate is known.
         *
         *     The rate comes from the AWS Price List API (cached 24 h). If it cannot be fetched and nothing
         *     is cached, ``estimated_cost_usd`` is null and ``price_status`` is ``unavailable``; the UI then
         *     asks the person to price the job by hand rather than showing a guessed figure. Free: no
         *     Comprehend call is made.
         */
        get: operations["label_estimate_dataset__dataset_id__labels_estimate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/labels/comprehend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Label a slice with Comprehend
         * @description Send up to ``max_records`` unlabelled records to Comprehend; call again until ``done``.
         *
         *     Resumable: successful labels and permanent failures are skipped; temporary failures have
         *     at most three attempts. Each call saves successes and failure counts before writing a
         *     labelled checkpoint. Requires ``confirm_cost=true`` so nothing is billed without the
         *     confirmation dialog.
         */
        post: operations["label_comprehend_dataset__dataset_id__labels_comprehend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/labels/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page through the review set
         * @description Records chosen for review, in review order, with whatever labels they currently carry.
         */
        get: operations["review_page_dataset__dataset_id__labels_review_get"];
        /**
         * Choose what to review by hand
         * @description Fix the review set.
         *
         *     ``none`` skips review, ``all`` reviews every record, ``sample`` picks ``size`` records (a
         *     count or a percent) with a fixed seed so the same request always yields the same subset.
         */
        put: operations["choose_review_dataset__dataset_id__labels_review_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/labels/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply reviewer labels
         * @description Set ``label_source="manual"`` on the given records. Comprehend's label is kept alongside.
         */
        post: operations["manual_labels_dataset__dataset_id__labels_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stored stage snapshots
         * @description CSV (and any converted Parquet) snapshots for collected, processed and labelled stages.
         */
        get: operations["list_checkpoints_dataset__dataset_id__checkpoints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/checkpoints/{stage}/parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert a CSV checkpoint to Parquet
         * @description Read the stage's CSV snapshot and write a Parquet twin next to it.
         */
        post: operations["convert_checkpoint_dataset__dataset_id__checkpoints__stage__parquet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download CSV
         * @description One row per original record: text, processed text, tokens, labels and provenance.
         */
        get: operations["export_csv_dataset__dataset_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Excel
         * @description Two sheets: ``data`` and ``impact`` (per-step statistics).
         */
        get: operations["export_excel_dataset__dataset_id__export_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/export.parquet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Parquet
         * @description Same rows as the CSV, typed and compressed. The format Task 2 should load.
         */
        get: operations["export_parquet_dataset__dataset_id__export_parquet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/report.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Task 1 report (Markdown)
         * @description Markdown with provenance, measured impact, labelling, and per-step strengths/limitations.
         */
        get: operations["export_report_dataset__dataset_id__report_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dataset/{dataset_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save to S3
         * @description Write ``dataset.parquet``, ``impact.json`` and ``manifest.json`` to the data bucket.
         */
        post: operations["save_dataset_dataset__dataset_id__save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * X spend so far
         * @description Totals from the local ledger (every billed read is recorded) plus the configured caps.
         *
         *     ``include_x_usage=true`` also asks X for its own usage figure. That call is free but only
         *     some tiers expose it, so ``x_usage`` is null when unavailable.
         */
        get: operations["spend_spend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent runs
         * @description Latest pipeline runs, newest first. Metadata only; record text is never stored here.
         */
        get: operations["recent_history_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_dataset_dataset_upload_post */
        Body_upload_dataset_dataset_upload_post: {
            /** File */
            file: string;
        };
        /**
         * CheckpointInfo
         * @description One stored file.
         */
        CheckpointInfo: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "collected" | "processed" | "labelled";
            /**
             * Format
             * @enum {string}
             */
            format: "csv" | "parquet";
            /** Uri */
            uri: string;
            /** Bytes */
            bytes: number;
            /**
             * Written At
             * Format: date-time
             */
            written_at: string;
        };
        /**
         * CheckpointList
         * @description Stage snapshots stored for a dataset, and where.
         */
        CheckpointList: {
            /**
             * Location
             * @enum {string}
             */
            location: "local" | "s3";
            /** Items */
            items: components["schemas"]["CheckpointInfo"][];
        };
        /**
         * ComprehendLabelRequest
         * @description One slice of Comprehend labelling. The client loops until ``done``.
         */
        ComprehendLabelRequest: {
            /**
             * Max Records
             * @default 250
             */
            max_records: number;
            /**
             * Confirm Cost
             * @description Must be true; the UI sets it after the confirmation dialog.
             * @default false
             */
            confirm_cost: boolean;
        };
        /**
         * DatasetMetrics
         * @description Shape of a dataset in numbers a reader can compare before/after.
         */
        DatasetMetrics: {
            /** Record Count */
            record_count: number;
            /** Vocab Size */
            vocab_size: number;
            /** Total Tokens */
            total_tokens: number;
            /** Avg Tokens */
            avg_tokens: number;
            /** Type Token Ratio */
            type_token_ratio: number;
            /** Length Histogram */
            length_histogram: {
                [key: string]: number;
            };
            /** Top Terms */
            top_terms: [
                string,
                number
            ][];
        };
        /**
         * DatasetSummary
         * @description Enough about a dataset for the UI header and the loader result.
         */
        DatasetSummary: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "x" | "huggingface" | "csv";
            /** Query */
            query: string | null;
            /** Window Start */
            window_start?: string | null;
            /** Window End */
            window_end?: string | null;
            /** Record Count */
            record_count: number;
            /** Labelled Count */
            labelled_count: number;
            /**
             * Filtered Out
             * @description Posts the source returned but that were not kept, by reason.
             */
            filtered_out?: {
                [key: string]: number;
            };
            /** Truncated Reason */
            truncated_reason: string | null;
            /** Estimated Cost Usd */
            estimated_cost_usd?: number | null;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /** Resume Request Id */
            resume_request_id?: string | null;
            /** Retry At */
            retry_at?: number | null;
            /** Warnings */
            warnings?: string[];
            /** Preview */
            preview: components["schemas"]["Record"][];
        };
        /**
         * ErrorResponse
         * @description Uniform error body. ``request_id`` lets a user quote the exact log lines.
         */
        ErrorResponse: {
            /** Error */
            error: string;
            /** Request Id */
            request_id: string;
        };
        /**
         * HealthResponse
         * @description Liveness plus, when ``diagnostics`` is true, the facts an operator checks first.
         *
         *     Operator fields are omitted unless diagnostics are enabled (local runtime by default)
         *     and the caller is authorized. Public liveness reveals no storage or enabled-service details.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Diagnostics */
            diagnostics: boolean;
            /** X Configured */
            x_configured: boolean;
            /** Auth Required */
            auth_required: boolean;
            /** Runtime */
            runtime?: string | null;
            /** Database */
            database?: string | null;
            /** Database Ephemeral */
            database_ephemeral?: boolean | null;
            /** Checkpoints */
            checkpoints?: ("local" | "s3") | null;
            /** Comprehend Enabled */
            comprehend_enabled?: boolean | null;
            /** Bedrock Enabled */
            bedrock_enabled?: boolean | null;
        };
        /**
         * HistoryRun
         * @description One row in the history panel.
         */
        HistoryRun: {
            /** Dataset Id */
            dataset_id: string;
            /** Source Type */
            source_type: string;
            /** Query */
            query: string;
            /** Record Count */
            record_count: number;
            /** Applied Steps */
            applied_steps: string[];
            /** Records Out */
            records_out: number;
            /** Vocab Before */
            vocab_before: number;
            /** Vocab After */
            vocab_after: number;
            /** Sentiment Agreement */
            sentiment_agreement: number | null;
            /** Embedding Drift */
            embedding_drift: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Created At */
            created_at: string;
        };
        /**
         * LabelEstimate
         * @description Units Comprehend would bill, and dollars when a current rate is known.
         *
         *     ``estimated_cost_usd`` and ``cost_per_unit_usd`` are null when the Price List lookup failed
         *     and nothing is cached; ``price_status`` explains why the UI must not show a figure.
         */
        LabelEstimate: {
            /** Records Total */
            records_total: number;
            /** Records Unlabelled */
            records_unlabelled: number;
            /**
             * Truncated Records
             * @default 0
             */
            truncated_records: number;
            /**
             * Prefix Labels
             * @default 0
             */
            prefix_labels: number;
            /** Records To Send */
            records_to_send: number;
            /**
             * Failed Total
             * @default 0
             */
            failed_total: number;
            /** Billable Units */
            billable_units: number;
            /** Unit Chars */
            unit_chars: number;
            /** Min Units Per Document */
            min_units_per_document: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number | null;
            /** Cost Per Unit Usd */
            cost_per_unit_usd: number | null;
            /**
             * Price Status
             * @enum {string}
             */
            price_status: "live" | "cached" | "stale" | "unavailable";
            /** Price Fetched At */
            price_fetched_at: string | null;
            /** Price Region */
            price_region?: string | null;
        };
        /**
         * LabelFailure
         * @description A persisted document failure; raw service messages stay in operator logs.
         */
        LabelFailure: {
            /** Record Id */
            record_id: string;
            /**
             * Code
             * @enum {string}
             */
            code: "document_rejected" | "temporarily_unavailable" | "missing_result";
            /** Retryable */
            retryable: boolean;
            /** Attempts */
            attempts: number;
        };
        /**
         * LabelProgress
         * @description Result of one Comprehend slice. ``cost_usd`` is null when no rate is known.
         */
        LabelProgress: {
            /**
             * Truncated Records
             * @default 0
             */
            truncated_records: number;
            /** Labelled In Call */
            labelled_in_call: number;
            /**
             * Attempted In Call
             * @default 0
             */
            attempted_in_call: number;
            /**
             * Failed In Call
             * @default 0
             */
            failed_in_call: number;
            /**
             * Failed Total
             * @default 0
             */
            failed_total: number;
            /** Failures */
            failures?: components["schemas"]["LabelFailure"][];
            /** Labelled Total */
            labelled_total: number;
            /** Remaining */
            remaining: number;
            /** Units Billed */
            units_billed: number;
            /** Cost Usd */
            cost_usd: number | null;
            /** Done */
            done: boolean;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /** Stop Reason */
            stop_reason?: string | null;
        };
        /**
         * LabelSummary
         * @description Label coverage, provenance, review progress and reviewer/Comprehend agreement.
         */
        LabelSummary: {
            /** Total */
            total: number;
            /** Labelled */
            labelled: number;
            /** By Source */
            by_source: {
                [key: string]: number;
            };
            /** By Label */
            by_label: {
                [key: string]: number;
            };
            /** Review Sample Size */
            review_sample_size: number;
            /** Reviewed */
            reviewed: number;
            /** Manual Vs Comprehend Agreement */
            manual_vs_comprehend_agreement: number | null;
            /** Disagreements */
            disagreements: number;
        };
        /**
         * LoadRequest
         * @description Fetch a dataset from a remote source.
         */
        LoadRequest: {
            /** Request Id */
            request_id?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "x" | "huggingface";
            /**
             * Limit
             * @description Records to fetch. Task 1 needs 500+.
             * @default 600
             */
            limit: number;
            /**
             * Query
             * @description Required for X. Operators like lang:en allowed.
             */
            query?: string | null;
            /**
             * Start Time
             * @description Oldest post to return (X only). Clamped to seven days ago, the limit of recent search.
             */
            start_time?: string | null;
            /**
             * End Time
             * @description Newest post to return (X only). Clamped to a few seconds ago.
             */
            end_time?: string | null;
        };
        /**
         * ManualLabelItem
         * @description One record's reviewed label.
         */
        ManualLabelItem: {
            /** Id */
            id: string;
            /**
             * Label
             * @enum {string}
             */
            label: "positive" | "negative" | "neutral" | "mixed";
        };
        /**
         * ManualLabelRequest
         * @description Reviewer decisions, applied atomically.
         */
        ManualLabelRequest: {
            /** Items */
            items: components["schemas"]["ManualLabelItem"][];
        };
        /**
         * PreprocessRequest
         * @description Run steps in the given order and measure impact.
         */
        PreprocessRequest: {
            /**
             * Steps
             * @description Step names in execution order.
             */
            steps: string[];
            options?: components["schemas"]["StepOptions"];
            /**
             * Explain
             * @description Ask Bedrock for a prose explanation.
             * @default true
             */
            explain: boolean;
        };
        /**
         * PreprocessResponse
         * @description Processed preview plus the full impact report.
         */
        PreprocessResponse: {
            /** Dataset Id */
            dataset_id: string;
            /** Applied Steps */
            applied_steps: string[];
            /** Record Count */
            record_count: number;
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            metrics_before: components["schemas"]["DatasetMetrics"];
            metrics_after: components["schemas"]["DatasetMetrics"];
            report: components["schemas"]["PublicImpactReport"];
            /** Preview */
            preview: components["schemas"]["Record"][];
        };
        /**
         * PublicImpactReport
         * @description A report safe to serialize for the current diagnostics policy.
         */
        PublicImpactReport: {
            sentiment?: components["schemas"]["SentimentComparison"] | null;
            /** Embedding Drift */
            embedding_drift?: number | null;
            /** Explanation */
            explanation?: string | null;
            /** Warnings */
            warnings?: string[];
            /** Steps */
            steps: components["schemas"]["PublicStepResult"][];
        };
        /**
         * PublicStepResult
         * @description User metrics with optional operator timing.
         */
        PublicStepResult: {
            /** Step Name */
            step_name: string;
            /** Records In */
            records_in: number;
            /** Records Out */
            records_out: number;
            /** Vocab Before */
            vocab_before: number;
            /** Vocab After */
            vocab_after: number;
            /** Avg Tokens Before */
            avg_tokens_before: number;
            /** Avg Tokens After */
            avg_tokens_after: number;
            /** Sample Diffs */
            sample_diffs?: [
                string,
                string
            ][];
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /**
         * Record
         * @description One text item.
         *
         *     ``label`` is the label to train on; ``label_source`` says where it came from so Task 2 can
         *     train on Comprehend labels and evaluate on manually reviewed ones. ``comprehend_label`` is
         *     kept separately so a manual override never erases what Comprehend said. ``tokens`` is
         *     populated once a tokenising step has run.
         */
        Record: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Label */
            label?: string | null;
            /** Label Source */
            label_source?: ("source" | "comprehend" | "manual") | null;
            /** Label Confidence */
            label_confidence?: number | null;
            /** Comprehend Label */
            comprehend_label?: string | null;
            /** Comprehend Confidence */
            comprehend_confidence?: number | null;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "x" | "huggingface" | "csv";
            /** Created At */
            created_at?: string | null;
            /** Tokens */
            tokens?: string[] | null;
        };
        /**
         * RecordPage
         * @description A page of original and processed records, joined by id.
         */
        RecordPage: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["RecordPair"][];
        };
        /**
         * RecordPair
         * @description Original next to processed. ``processed`` is null when the record was dropped.
         */
        RecordPair: {
            original: components["schemas"]["Record"];
            processed: components["schemas"]["Record"] | null;
        };
        /**
         * ReviewPage
         * @description A page of records chosen for manual review, in review order.
         */
        ReviewPage: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["Record"][];
        };
        /**
         * ReviewRequest
         * @description Which records a person will review by hand.
         */
        ReviewRequest: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "none" | "all" | "sample";
            /**
             * Size
             * @default 150
             */
            size: number;
            /**
             * Unit
             * @default count
             * @enum {string}
             */
            unit: "count" | "percent";
            /**
             * Seed
             * @default 7
             */
            seed: number;
        };
        /**
         * SaveResponse
         * @description Where the saved folder landed.
         */
        SaveResponse: {
            /** Uri */
            uri?: string | null;
        };
        /**
         * SentimentComparison
         * @description Baseline scorer output before vs after preprocessing.
         */
        SentimentComparison: {
            /** Agreement */
            agreement?: number | null;
            /**
             * Comparable Records
             * @default 0
             */
            comparable_records: number;
            /**
             * Shared Records
             * @default 0
             */
            shared_records: number;
            /** Distribution Before */
            distribution_before: {
                [key: string]: number;
            };
            /** Distribution After */
            distribution_after: {
                [key: string]: number;
            };
        };
        /**
         * SessionRequest
         * @description Operator credential, submitted once over HTTPS and never stored by the browser.
         */
        SessionRequest: {
            /**
             * Key
             * Format: password
             */
            key: string;
        };
        /**
         * SessionResponse
         * @description Short-lived bearer credential. Kept only in browser memory.
         */
        SessionResponse: {
            /** Token */
            token: string;
            /**
             * Expires In
             * @default 3600
             */
            expires_in: number;
        };
        /**
         * SpendSummary
         * @description Local ledger totals plus caps. ``x_usage`` is X's own figure when the tier exposes it.
         */
        SpendSummary: {
            /** Today Reads */
            today_reads: number;
            /** Today Cost Usd */
            today_cost_usd: number;
            /** Month Reads */
            month_reads: number;
            /** Month Cost Usd */
            month_cost_usd: number;
            /** Cap Per Fetch */
            cap_per_fetch: number;
            /** Cap Per Day */
            cap_per_day: number;
            /** Remaining Today */
            remaining_today: number;
            /** Cost Per Read Usd */
            cost_per_read_usd: number;
            /** X Usage */
            x_usage?: {
                [key: string]: unknown;
            } | null;
            /** X Configured */
            x_configured: boolean;
        };
        /**
         * StepInfo
         * @description Step catalogue entry for the UI toggle list.
         */
        StepInfo: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Strengths */
            strengths: string;
            /** Limitations */
            limitations: string;
        };
        /**
         * StepOptions
         * @description Per-step knobs the UI exposes. Unset means the step default.
         */
        StepOptions: {
            /**
             * Missing Data Strategy
             * @default drop
             * @enum {string}
             */
            missing_data_strategy: "drop" | "fill";
            /**
             * Missing Data Fill Value
             * @description Placeholder written into empty records when the strategy is 'fill'. It becomes a token in the vocabulary, so pick something the corpus cannot contain.
             * @default [EMPTY]
             */
            missing_data_fill_value: string;
            /**
             * Keep Negations
             * @default true
             */
            keep_negations: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    load_dataset_dataset_load_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_dataset_dataset_upload_post: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_dataset_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_dataset_dataset__dataset_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_records_dataset__dataset_id__records_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                /** @description Case-insensitive substring on original text */
                search?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordPage"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_steps_steps_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepInfo"][];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preprocess_dataset__dataset_id__preprocess_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreprocessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreprocessResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    label_summary_dataset__dataset_id__labels_summary_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelSummary"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    label_estimate_dataset__dataset_id__labels_estimate_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelEstimate"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    label_comprehend_dataset__dataset_id__labels_comprehend_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComprehendLabelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelProgress"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    review_page_dataset__dataset_id__labels_review_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPage"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    choose_review_dataset__dataset_id__labels_review_put: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelSummary"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    manual_labels_dataset__dataset_id__labels_manual_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualLabelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelSummary"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_checkpoints_dataset__dataset_id__checkpoints_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointList"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    convert_checkpoint_dataset__dataset_id__checkpoints__stage__parquet_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
                stage: "collected" | "processed" | "labelled";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointInfo"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_csv_dataset__dataset_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_excel_dataset__dataset_id__export_xlsx_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_parquet_dataset__dataset_id__export_parquet_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_report_dataset__dataset_id__report_md_get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_dataset_dataset__dataset_id__save_post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    spend_spend_get: {
        parameters: {
            query?: {
                include_x_usage?: boolean;
            };
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendSummary"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recent_history_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryRun"][];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
